dependencies:
- name: zookeeper
  version: 1.2.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: druid.zookeeper.enabled,zookeeper.enabled
- name: mysql
  version: 0.10.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: druid.mysql.enabled,mysql.enabled
